steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=Dockerfile
      - --build-arg
      - E5_BUNDLE_URL=${_E5_BUNDLE_URL}
      - --tag
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA
      - .
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA
  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA
      - --project=$PROJECT_ID
      - --region=${_DEPLOY_REGION}
      - --platform=${_PLATFORM}
      - --quiet

images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
